task: 'zju_mocap_blur'
subject: 'p386'
experiment: 'exfman'


##############################################3
## Data Configuration

train:
  dataset_module: 'core.data.human_nerf.train'
  dataset: 'zju_386_train'
  lossweights:
    blur_lpips_uncert: 1.0
    blur_mse_uncert: 0.2
    event_mse_uncert: 0.02
    pose_reg: 0.01
    sparsity_reg: 1.0
    alpha_mse_uncert: 1.0


progress:
  dataset_module: 'core.data.human_nerf.train'
  dataset: 'zju_386_test'

movement:
  dataset_module: 'core.data.human_nerf.eval'
  dataset: 'zju_386_test'

freeview:
  dataset_module: 'core.data.human_nerf.freeview'
  dataset: 'zju_386_test'

tpose:
  dataset_module: 'core.data.human_nerf.tpose'
  dataset: 'zju_386_test'

text:
  dataset_module: 'core.data.human_nerf.text'
  dataset: 'zju_377_test'

bgcolor: [255., 255., 255.]
resize_img_scale: 0.5

# reduce the size of patch from 32x32 to 20x20 to fit in a single gpu
patch:
  size: 20      # [Patch] size of patch

pose_decoder:
  kick_in_iter: 10000000000